name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if applicable)
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Change if needed

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Adjust for your build command

      - name: Copy files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          api-key: ${{ secrets.HOSTINGER_API_KEY }}
          virtual-machine: ${{ vars.HOSTINGER_VM_ID }}
          source: "build/*"
          target: "/var/www/html"

      - name: Restart NGINX
        uses: appleboy/ssh-action@v0.1.7
        with:
          api-key: ${{ secrets.HOSTINGER_API_KEY }}
          virtual-machine: ${{ vars.HOSTINGER_VM_ID }}
          script: |
            sudo systemctl reload nginx

